### ISSUE TITLE
Gesture / distance sensor not functional

### ISSUE THREAD

**Issue by TheKitty** [adafruit/Adafruit_CircuitPython_CLUE#13] opened 2020-02-10 02:10 UTC
Debra (@geekmomprojects on Twitter) has been trying to use the Light + Gesture + Proximity: APDS9960 and it has been either returning no value (distance) or irregular values (gesture). The underlying library is quite old (9/2017) and may not be entirely functional. I'll post this on that library too.

**Comment by TheKitty** [comment] 2020-02-10 02:17
Filed https://github.com/adafruit/Adafruit_CircuitPython_APDS9960/issues/16

**Comment by geekmomprojects** [comment] 2020-02-10 07:11
When running the following sample code from the adafruit_clue library documentation to retrieve data from the gesture sensor:

```
from adafruit_clue import clue

while True:
    print("Gesture: {}".format(clue.gesture))
    print("Proximity: {}".format(clue.proximity))
```

I get results for proximity but almost no nonzero results for gesture. To get any nonzero gesture readings at all, the gestures need to be very close (millimeters) away from the sensor.

**Comment by ladyada** [comment] 2020-02-10 16:24
hi please try running the example in this repo
https://github.com/adafruit/Adafruit_CircuitPython_APDS9960
as the issue isn't the CLUE library but the APDS library  :)

**Comment by ladyada** [comment] 2020-02-10 16:25
closing this issue - please continue all discussion 
https://github.com/adafruit/Adafruit_CircuitPython_APDS9960/issues/16
so that we have one thread to follow - thank you :)

**Closed by ladyada** 2020-02-10 16:25 UTC
